src/hooks/useWalletSync.ts
remove loginModal when logging in to portkey
=> feat: remove loginModal when logging in to portkey

src/pagesComponents/Detail/component/Listings/index.tsx, src/pagesComponents/Detail/hooks/useDetail.ts, src/pagesComponents/Detail/hooks/useIntervalRequestForListings.ts, src/pagesComponents/Detail/views/DetailPc/index.tsx
=> feat: optimize interface requests

src/pagesComponents/Detail/component/Offers/index.tsx, src/pagesComponents/Detail/component/SaleModal/comps/SummaryInfo.tsx, src/pagesComponents/Detail/component/SaleModal/index.tsx, src/utils/format.ts
price display and sale listing price
=> feat: price display and sale listing price

src/pagesComponents/Detail/component/Offers/index.tsx, src/pagesComponents/Detail/component/SaleModal/comps/SummaryInfo.tsx, src/pagesComponents/Detail/component/SaleModal/index.tsx, src/utils/format.ts
price display and sale listing price
=> feat: price display and sale listing price (#24)

src/api/fetch.ts, src/constants/promptMessage.ts, src/pagesComponents/DropsDetail/component/BasicInformation/index.tsx, src/pagesComponents/DropsDetail/component/DetailCard/index.tsx, src/pagesComponents/DropsDetail/component/DropsMint/index.tsx, src/pagesComponents/DropsDetail/component/EventLimitCard/index.tsx, src/pagesComponents/DropsDetail/component/EventLimitCountdownMobile/index.tsx, src/pagesComponents/DropsDetail/component/EventLimitCountdownPc/index.tsx, src/pagesComponents/DropsDetail/component/MintModal/index.tsx, src/pagesComponents/DropsDetail/component/ShareModal/index.tsx, src/pagesComponents/DropsDetail/hooks/useClaimDrop.ts, src/pagesComponents/DropsDetail/hooks/useInitialization.ts, src/pagesComponents/DropsDetail/utils/getDropDetail.ts, src/pagesComponents/DropsDetail/utils/getDropQuota.ts, src/pagesComponents/DropsDetail/views/DropsDetailMobile/index.tsx, src/pagesComponents/DropsDetail/views/DropsDetailPc/index.tsx, src/utils/deserializeLog.ts
=> feat: api and ClaimDrop contract

src/components/Balance/index.tsx, src/components/NftInfoList/index.tsx, src/components/Summary/index.tsx, src/components/Summary/useGetTransitionFee.ts, src/contract/drop.ts, src/contract/formatErrorMsg.ts, src/pagesComponents/Collections/components/CollectionsTable/index.tsx, src/pagesComponents/DropsDetail/component/BasicInformation/index.tsx, src/pagesComponents/DropsDetail/component/DropsMint/index.tsx, src/pagesComponents/DropsDetail/component/MintModal/index.tsx, src/pagesComponents/DropsDetail/hooks/useClaimDrop.ts, src/pagesComponents/DropsDetail/utils/getDropQuota.ts
=> feat: drop Contract

src/constants/index.ts, src/contract/type.ts, src/pagesComponents/DropsDetail/component/MintModal/index.tsx, src/utils/deserializeLog.ts
=> feat: mint result modal

src/pagesComponents/DropsDetail/component/DropsMint/index.tsx, src/pagesComponents/DropsDetail/component/MintModal/index.tsx, src/pagesComponents/DropsDetail/hooks/useClaimDrop.ts, src/pagesComponents/DropsDetail/hooks/useInitialization.ts
add jump to drops when Canceled
=> feat: add jump to drops when Canceled

src/pagesComponents/DropsDetail/component/DetailCard/index.tsx
=> feat: drop introduction UI

src/pagesComponents/DropsDetail/hooks/useInitialization.ts
=> feat: loading

src/pagesComponents/Drops/ActivitySwiper/index.tsx, src/pagesComponents/Drops/EventList/index.tsx, src/pagesComponents/DropsDetail/component/ShareModal/index.tsx
=> Feature/dev 1.6.0

src/contract/formatErrorMsg.ts, src/pagesComponents/DropsDetail/component/DropsMint/index.tsx, src/pagesComponents/DropsDetail/component/MintModal/index.tsx, src/pagesComponents/DropsDetail/hooks/useInitialization.ts, src/pagesComponents/DropsDetail/utils/getDropDetail.ts, src/pagesComponents/DropsDetail/utils/getDropQuota.ts, src/pagesComponents/DropsDetail/utils/getMintState.ts
=> feat: optimize process

src/pagesComponents/DropsDetail/component/EventLimitCountdownMobile/index.tsx, src/pagesComponents/DropsDetail/component/EventLimitCountdownPc/index.tsx, src/pagesComponents/DropsDetail/utils/getDropDetail.ts, src/pagesComponents/DropsDetail/utils/getDropQuota.ts, src/pagesComponents/DropsDetail/views/DropsDetailPc/index.tsx
=> feat: remove log

src/baseComponents/SkeletonImage/index.tsx, src/pagesComponents/DropsDetail/component/Banner/index.tsx, src/pagesComponents/DropsDetail/component/DetailCard/index.tsx
=> feat: add SkeletonImage

src/baseComponents/Button/index.tsx, src/pagesComponents/DropsDetail/component/DropsMint/index.tsx, src/pagesComponents/DropsDetail/component/MintModal/index.tsx, src/pagesComponents/DropsDetail/component/ShareModal/index.tsx, src/pagesComponents/DropsDetail/hooks/useClaimDrop.ts, src/pagesComponents/DropsDetail/utils/getDropQuota.ts
=> feat: add Throttle

src/pagesComponents/DropsDetail/component/MintModal/index.tsx, src/pagesComponents/DropsDetail/hooks/useClaimDrop.ts, src/utils/aelfUtils.tsx
=> feat: drop approve

src/pagesComponents/DropsDetail/component/MintModal/index.tsx
=> feat: mint remove tokenBalance

src/contract/formatErrorMsg.ts
=> feat: replace DropMinted

src/components/ResultModal/index.tsx, src/pagesComponents/DropsDetail/component/MintModal/index.tsx
=> feat: update Drop Detail

src/pagesComponents/DropsDetail/component/DropsMint/index.tsx, src/pagesComponents/DropsDetail/component/EventLimitInformation/index.tsx
=> feat: optimization Tooltip style

src/pagesComponents/DropsDetail/component/MintModal/index.tsx
=> feat: format mintPrice

src/components/ResultModal/index.tsx, src/pagesComponents/Drops/ActivitySwiper/index.tsx, src/pagesComponents/Drops/EventItem/index.tsx, src/pagesComponents/Drops/SelectType/style.module.css, src/pagesComponents/DropsDetail/component/Banner/index.tsx, src/pagesComponents/DropsDetail/component/BasicInformation/index.tsx, src/pagesComponents/DropsDetail/component/EventLimitInformation/index.module.css, src/pagesComponents/DropsDetail/component/EventLimitInformation/index.tsx, src/pagesComponents/DropsDetail/component/MintModal/index.tsx, src/pagesComponents/DropsDetail/views/DropsDetailMobile/index.tsx, src/pagesComponents/ExploreItems/components/CollectionsInfo/index.tsx, tailwind.config.js
=> feat: fix detail page UI problem

src/components/ResultModal/index.tsx, src/pagesComponents/DropsDetail/component/EventLimitInformation/index.tsx, src/styles/base.css
=> feat: update ant-message zIndex

src/pagesComponents/ExploreItems/ExploreItems.tsx
=> fix: 🐛 filter z-index

src/components/CollectionsSwiper/index.tsx, src/components/ImgLoading/ImgLoadingEnhance.tsx, src/components/NftInfoCard/index.tsx, src/components/NftInfoList/index.tsx, src/components/NftInfoListCard/index.tsx, src/pagesComponents/Detail/component/BuyNowModal/components/PriceInfo/index.tsx, src/pagesComponents/Detail/component/Picture/Picture.tsx, src/pagesComponents/Detail/component/SaleModal/comps/NFTSaleInfoCard.tsx, src/pagesComponents/Detail/component/SaleModal/modal/EditListingSuccessModal.tsx, src/pagesComponents/Detail/component/SaleModal/modal/InValidListMsgModal.tsx, src/pagesComponents/Detail/component/SaleModal/modal/ListingSuccessModal.tsx, src/pagesComponents/Detail/component/TransferModal/index.tsx, src/pagesComponents/DropsDetail/component/CollectionInformation/index.tsx, src/pagesComponents/SetSale/components/BackTitle/BackTitle.tsx, src/pagesComponents/SetSale/components/SetItems/modals/InValidListMsgModal/index.tsx
🐞 Fixed the item details page occasionally did not display images #130
=> fix: use new Image components to load image with ipfs

next.config.js, src/api/fetch.ts, src/assets/resString/index.ts, src/components/Header/style.css, src/components/ProgressSteps/index.tsx, src/components/SyncChainModal/CreateNFTSyncChainModal.tsx, src/components/SyncChainModal/useCreateNFTForModal.ts, src/contract/type.ts, src/hooks/useCreate.ts, src/pagesComponents/Collections/Hooks/useCollections.ts, src/pagesComponents/CreateCollection/index.tsx, src/pagesComponents/CreateItem/index.tsx, src/pagesComponents/Detail/component/Picture/Picture.tsx, src/pagesComponents/ExploreItem/ExploreItem.tsx, src/pagesComponents/ExploreItem/components/CollectionItemsSearch/index.tsx, src/pagesComponents/ExploreItem/components/NFTList/index.tsx, src/pagesComponents/ExploreItem/constant.ts, src/pagesComponents/MyCollections/index.tsx, tsconfig.json
optimize create nft on sideChain
=> feat: optimize create nft

next.config.js, src/api/fetch.ts, src/assets/resString/index.ts, src/components/Header/style.css, src/components/ProgressSteps/index.tsx, src/components/SyncChainModal/CreateNFTSyncChainModal.tsx, src/components/SyncChainModal/useCreateNFTForModal.ts, src/contract/type.ts, src/hooks/useCreate.ts, src/pagesComponents/Collections/Hooks/useCollections.ts, src/pagesComponents/CreateCollection/index.tsx, src/pagesComponents/CreateItem/index.tsx, src/pagesComponents/Detail/component/Picture/Picture.tsx, src/pagesComponents/ExploreItem/ExploreItem.tsx, src/pagesComponents/ExploreItem/components/CollectionItemsSearch/index.tsx, src/pagesComponents/ExploreItem/components/NFTList/index.tsx, src/pagesComponents/ExploreItem/constant.ts, src/pagesComponents/MyCollections/index.tsx, tsconfig.json
1、Item is first created on the sidechain close #135 
2、The explore page list component status is recorded in history 
3、Import aelf-design
=> NFT created on the sideChain

nextLint.yml
=> feat: add nextlint yml

src/pagesComponents/CreateCollectionV2/index.tsx
- fix: change upload component import path
=> fix: change upload component import path

src/pagesComponents/CreateItemByAI/hooks/useGeneratePictures.ts
use chainId as the create AI picture's params
=> fix: replace chainId to tdvw

package.json, src/components/CollectionList/CollectionList.tsx, src/components/Header/index.tsx, src/hooks/useCreate.ts, src/hooks/useWalletSync.ts, src/pagesComponents/CreateItemByAI/hooks/useGeneratePictures.ts, src/pagesComponents/Detail/component/BidModal/index.tsx, src/pagesComponents/Detail/hooks/useIntervalRequestForBid.ts, src/pagesComponents/Detail/hooks/useIntervalRequestForListings.ts, src/pagesComponents/Detail/hooks/useIntervalRequestForOffers.ts, src/pagesComponents/ExploreItem/components/ActivityListTable/index.tsx, src/pagesComponents/FailedAIOrder/index.tsx, src/pagesComponents/Profiles/ActivityItem.tsx, src/socket/index.ts, src/utils/aelfUtils.tsx, yarn.lock
=> feat:batch approve nft symbol

src/api/types.ts, src/contract/market.ts, src/contract/type.ts, src/pagesComponents/Detail/component/BuyNowModal/components/PriceInfo/index.tsx, src/pagesComponents/Detail/component/ExchangeModal/components/DealSummary/index.tsx, src/pagesComponents/Detail/component/ExchangeModal/index.tsx, src/pagesComponents/Detail/component/SaleModal/utils/batchDeList.ts, src/pagesComponents/Detail/hooks/useGetTransitionFee.ts, src/pagesComponents/ExploreItem/components/CollectionItemsSearch/index.tsx, src/pagesComponents/Profiles/ActivityItem.tsx, src/pagesComponents/Profiles/MoreItem.tsx, src/pagesComponents/Profiles/Profile.module.css, src/pagesComponents/Profiles/components/CancelListingModal/index.tsx, src/pagesComponents/Profiles/components/OffersOrListingTable/index.tsx, src/pagesComponents/Profiles/components/ProfileBanner/ProfileBanner.tsx, src/pagesComponents/Profiles/hooks/useActionService.ts, src/pagesComponents/Profiles/hooks/useOfferTable.tsx, src/pagesComponents/Profiles/hooks/useProfilePageService.ts, src/pagesComponents/Profiles/index.tsx
- In the user profile, the user can perform some actions such as canceling the offer made and dealing with the offer.
-  In the user profile, user can save avatar and banner
=> feat:cancel all offers and cancel all listings

src/api/types.ts, src/contract/market.ts, src/contract/type.ts, src/pagesComponents/Detail/component/BuyNowModal/components/PriceInfo/index.tsx, src/pagesComponents/Detail/component/ExchangeModal/components/DealSummary/index.tsx, src/pagesComponents/Detail/component/ExchangeModal/index.tsx, src/pagesComponents/Detail/component/SaleModal/utils/batchDeList.ts, src/pagesComponents/Detail/hooks/useGetTransitionFee.ts, src/pagesComponents/ExploreItem/components/CollectionItemsSearch/index.tsx, src/pagesComponents/Profiles/ActivityItem.tsx, src/pagesComponents/Profiles/MoreItem.tsx, src/pagesComponents/Profiles/Profile.module.css, src/pagesComponents/Profiles/components/CancelListingModal/index.tsx, src/pagesComponents/Profiles/components/OffersOrListingTable/index.tsx, src/pagesComponents/Profiles/components/ProfileBanner/ProfileBanner.tsx, src/pagesComponents/Profiles/hooks/useActionService.ts, src/pagesComponents/Profiles/hooks/useOfferTable.tsx, src/pagesComponents/Profiles/hooks/useProfilePageService.ts, src/pagesComponents/Profiles/index.tsx
In the user profile, the user can perform some actions such as canceling the offer made and dealing with the offer , user can edit banner and avatar.
As a user, I want to see all my activities and perform some actions in the profile.So, this new feature solves this problem.
**Features:**
- user can perform some actions such as canceling the offer made and dealing with the offer.
- user can save avatar and banner.
=> Release 2.6.0

src/api/fetch.ts, src/components/Summary/useGetTransitionFee.ts, src/constants/common.ts, src/pagesComponents/Detail/component/BuyNowModal/components/TotalPrice/index.tsx, src/pagesComponents/Detail/component/ExchangeModal/components/DealSummary/index.tsx, src/pagesComponents/Detail/component/ExchangeModal/index.tsx, src/pagesComponents/Detail/component/SaleModal/comps/SummaryInfo.tsx, src/pagesComponents/Detail/component/SaleModal/index.tsx
Feature：
add royalty for the sell modal
=> feat: add royalty for sell modal

src/api/types.ts, src/pagesComponents/Collections/components/CollectionsTable/index.tsx, src/pagesComponents/Detail/component/BuyNowModal/components/InputQuantity/index.tsx, src/pagesComponents/Detail/component/BuyNowModal/components/PriceInfo/index.tsx, src/pagesComponents/Detail/component/BuyNowModal/components/Summary/index.tsx, src/pagesComponents/Detail/component/BuyNowModal/components/TotalPrice/index.tsx, src/pagesComponents/Detail/component/BuyNowModal/index.tsx, src/pagesComponents/Detail/component/OfferModal/index.tsx, src/pagesComponents/Detail/component/SaleModal/comps/SetPrice.tsx, src/pagesComponents/Detail/component/SaleModal/hooks/useSetPrice.ts, src/pagesComponents/Detail/component/SaleModal/index.tsx, src/pagesComponents/Home/components/HotNFTs/index.tsx, src/pagesComponents/Profiles/ActivityItem.tsx
- The home page shows the NFT price more friendly
- Some display logics of detail's modals have been optimized
=> feature: Some display logics of modals have been optimized

src/api/types.ts, src/pagesComponents/Collections/components/CollectionsTable/index.tsx, src/pagesComponents/Detail/component/BuyNowModal/components/InputQuantity/index.tsx, src/pagesComponents/Detail/component/BuyNowModal/components/PriceInfo/index.tsx, src/pagesComponents/Detail/component/BuyNowModal/components/Summary/index.tsx, src/pagesComponents/Detail/component/BuyNowModal/components/TotalPrice/index.tsx, src/pagesComponents/Detail/component/BuyNowModal/index.tsx, src/pagesComponents/Detail/component/OfferModal/index.tsx, src/pagesComponents/Detail/component/SaleModal/comps/SetPrice.tsx, src/pagesComponents/Detail/component/SaleModal/hooks/useSetPrice.ts, src/pagesComponents/Detail/component/SaleModal/index.tsx, src/pagesComponents/Home/components/HotNFTs/index.tsx, src/pagesComponents/Profiles/ActivityItem.tsx
Feature:
- The home page shows the NFT price more friendly
- Some display logics of detail's modals have been optimized
=> Some display logics of detail's modals have been optimized

src/pagesComponents/Detail/component/DetailCard/DetailsCard.tsx
The issue of incorrect Total Supply display has been fixed
=> fix: Total Supply shows wrongly

.github/workflows/testnet-package.yaml, src/components/Header/components/WalletDropdown/index.tsx, src/components/Header/index.tsx, src/providers/provider.tsx, src/store/reducer/balance.ts, src/store/reducer/userInfo.ts, src/store/store.ts
User info maybe be undefined  when TSM  link to Forest
=> fix: user info maybe be undefined  when tsm link to forest

src/pagesComponents/ExploreItem/components/ActivityListTable/index.tsx
=> fix: explorer url change

src/pagesComponents/ExploreItem/components/NFTList/index.tsx, src/pagesComponents/Home/components/Banner/index.tsx
=> list price show bugfixed
